import type { Messages } from "@/lib/i18n";

/** Strings needed by `ShopCheckout` only — pass from the server to avoid bundling full locale JSON on the client. */
export type ShopCheckoutCopy = Pick<
  Messages,
  | "shopShowing"
  | "shopProductCount"
  | "shopSortByLabel"
  | "shopViewGridLarge"
  | "shopViewGridSmall"
  | "shopViewList"
  | "shopFilterProductType"
  | "shopFilterProductTypeEn"
  | "shopFilterAllTypes"
  | "shopSearchPlaceholder"
  | "shopSearchLabel"
  | "shopSortDefault"
  | "shopSortPriceAsc"
  | "shopSortPriceDesc"
  | "shopAddToCart"
  | "shopViewDetails"
  | "shopClose"
  | "shopQuantityLabel"
  | "shopDecreaseQty"
  | "shopIncreaseQty"
  | "shopWhyWeLoveIt"
  | "shopHowToUse"
  | "shopSalonPick"
  | "shopHoldMeter"
  | "shopShineMeter"
  | "shopInSalonPickup"
  | "shopTrustManualReview"
  | "shopCartTitle"
  | "shopCartEmpty"
  | "shopCartSubtotal"
  | "shopCartCheckout"
  | "shopStickyViewCart"
  | "shopRetailAvailability"
  | "shopCheckoutTitle"
  | "shopCheckoutEmptyCart"
  | "shopOrderSummaryLabel"
  | "shopChangeQty"
  | "shopStaticCheckoutNote"
  | "shopCustomerNameLabel"
  | "shopContactEmailOptional"
  | "shopContactPhoneOption"
  | "shopContactEmailHint"
  | "shopContactPhoneHint"
  | "shopContactPhoneInvalid"
  | "shopContactEmailInvalid"
  | "shopContactRequired"
  | "shopPaymentLabel"
  | "shopPaymentHintAfterOrder"
  | "shopPaymentAccountLabel"
  | "shopPaymentMpayMerchantLabel"
  | "shopPaymentQrAlt"
  | "shopPaymentQrCaption"
  | "shopPayLocalCta"
  | "shopPayCardCta"
  | "shopWechatOrder"
  | "shopWechatOrderCopied"
  | "shopMailOrder"
  | "catShampoo"
  | "catConditioner"
  | "catTreatment"
  | "catStyling"
  | "catUncategorized"
  | "shopNoFilterMatch"
  | "shopClearFilters"
  | "shopNoProducts"
  | "shopEmptyCta"
  | "shopLocalPayFlowTitle"
  | "shopPayNextSteps"
  | "shopOrderIdLabel"
  | "shopAmountLabel"
  | "shopPlaceAnotherOrder"
  | "shopProofPreviewLabel"
  | "shopProofUploadLabel"
  | "shopProofUploadHint"
  | "shopProofChooseFile"
  | "shopProofNoFile"
  | "shopProofChangeFile"
  | "shopProofUploading"
  | "shopProofSubmit"
  | "shopProofReceived"
  | "shopProofReviewPending"
>;

export function pickShopCheckoutCopy(t: Messages): ShopCheckoutCopy {
  return {
    shopShowing: t.shopShowing,
    shopProductCount: t.shopProductCount,
    shopSortByLabel: t.shopSortByLabel,
    shopViewGridLarge: t.shopViewGridLarge,
    shopViewGridSmall: t.shopViewGridSmall,
    shopViewList: t.shopViewList,
    shopFilterProductType: t.shopFilterProductType,
    shopFilterProductTypeEn: t.shopFilterProductTypeEn,
    shopFilterAllTypes: t.shopFilterAllTypes,
    shopSearchPlaceholder: t.shopSearchPlaceholder,
    shopSearchLabel: t.shopSearchLabel,
    shopSortDefault: t.shopSortDefault,
    shopSortPriceAsc: t.shopSortPriceAsc,
    shopSortPriceDesc: t.shopSortPriceDesc,
    shopAddToCart: t.shopAddToCart,
    shopViewDetails: t.shopViewDetails,
    shopClose: t.shopClose,
    shopQuantityLabel: t.shopQuantityLabel,
    shopDecreaseQty: t.shopDecreaseQty,
    shopIncreaseQty: t.shopIncreaseQty,
    shopWhyWeLoveIt: t.shopWhyWeLoveIt,
    shopHowToUse: t.shopHowToUse,
    shopSalonPick: t.shopSalonPick,
    shopHoldMeter: t.shopHoldMeter,
    shopShineMeter: t.shopShineMeter,
    shopInSalonPickup: t.shopInSalonPickup,
    shopTrustManualReview: t.shopTrustManualReview,
    shopCartTitle: t.shopCartTitle,
    shopCartEmpty: t.shopCartEmpty,
    shopCartSubtotal: t.shopCartSubtotal,
    shopCartCheckout: t.shopCartCheckout,
    shopStickyViewCart: t.shopStickyViewCart,
    shopRetailAvailability: t.shopRetailAvailability,
    shopCheckoutTitle: t.shopCheckoutTitle,
    shopCheckoutEmptyCart: t.shopCheckoutEmptyCart,
    shopOrderSummaryLabel: t.shopOrderSummaryLabel,
    shopChangeQty: t.shopChangeQty,
    shopStaticCheckoutNote: t.shopStaticCheckoutNote,
    shopCustomerNameLabel: t.shopCustomerNameLabel,
    shopContactEmailOptional: t.shopContactEmailOptional,
    shopContactPhoneOption: t.shopContactPhoneOption,
    shopContactEmailHint: t.shopContactEmailHint,
    shopContactPhoneHint: t.shopContactPhoneHint,
    shopContactPhoneInvalid: t.shopContactPhoneInvalid,
    shopContactEmailInvalid: t.shopContactEmailInvalid,
    shopContactRequired: t.shopContactRequired,
    shopPaymentLabel: t.shopPaymentLabel,
    shopPaymentHintAfterOrder: t.shopPaymentHintAfterOrder,
    shopPaymentAccountLabel: t.shopPaymentAccountLabel,
    shopPaymentMpayMerchantLabel: t.shopPaymentMpayMerchantLabel,
    shopPaymentQrAlt: t.shopPaymentQrAlt,
    shopPaymentQrCaption: t.shopPaymentQrCaption,
    shopPayLocalCta: t.shopPayLocalCta,
    shopPayCardCta: t.shopPayCardCta,
    shopWechatOrder: t.shopWechatOrder,
    shopWechatOrderCopied: t.shopWechatOrderCopied,
    shopMailOrder: t.shopMailOrder,
    catShampoo: t.catShampoo,
    catConditioner: t.catConditioner,
    catTreatment: t.catTreatment,
    catStyling: t.catStyling,
    catUncategorized: t.catUncategorized,
    shopNoFilterMatch: t.shopNoFilterMatch,
    shopClearFilters: t.shopClearFilters,
    shopNoProducts: t.shopNoProducts,
    shopEmptyCta: t.shopEmptyCta,
    shopLocalPayFlowTitle: t.shopLocalPayFlowTitle,
    shopPayNextSteps: t.shopPayNextSteps,
    shopOrderIdLabel: t.shopOrderIdLabel,
    shopAmountLabel: t.shopAmountLabel,
    shopPlaceAnotherOrder: t.shopPlaceAnotherOrder,
    shopProofPreviewLabel: t.shopProofPreviewLabel,
    shopProofUploadLabel: t.shopProofUploadLabel,
    shopProofUploadHint: t.shopProofUploadHint,
    shopProofChooseFile: t.shopProofChooseFile,
    shopProofNoFile: t.shopProofNoFile,
    shopProofChangeFile: t.shopProofChangeFile,
    shopProofUploading: t.shopProofUploading,
    shopProofSubmit: t.shopProofSubmit,
    shopProofReceived: t.shopProofReceived,
    shopProofReviewPending: t.shopProofReviewPending,
  };
}
